name: Run Chatbot Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build Chatbot
        run: g++ -o chatbot Agent.cpp

      - name: Build and Run Tests
        run: g++ -DUNIT_TEST -o test_app tests_chatbot.cpp Agent.cpp && ./test_app
